apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    env:
    - name: MY_PROJECT_NAME
      value: "test"
    - name: SOME_PATH
      value: "/home"
    - name: DD_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP # we can assign default variables values that allow us to change it dynamically 
    resources:
      requests:
        memory: "64Mi"
        cpu: "200m" # 1000m = 1 core CPU 
      limits:
        memory: "128Mi"
        cpu: "500m" # max amount of CPU is is overloaded the linux kernel kill the process
    readinessProbe: # if the instance don't response the http call kubernetes wait for redirect trafict to this instance
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 20
    ports:
    - containerPort: 80